main:
  - name: 首页
    url: /
    weight: 10
  - name: 研究方向
    url: /#research
    weight: 20
  - name: 代表性论文
    url: /#publications
    weight: 30
  - name: 研究视频
    url: /projects/
    weight: 40
  - name: 经历与荣誉
    url: /experience/
    weight: 50
