# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: '刘润潇，北京航空航天大学控制科学与工程博士研究生，研究多无人机协同吊运与图像视觉伺服控制。'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: '刘润潇 · Runxiao Liu'

# Site footer
footer:
  copyright:
    notice: '© {year} 刘润潇'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '2006年1月2日'
  time_format: '15:04'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
